<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Aprovisionamiento" targetNamespace="urn:com.ec.tvcable.switch_aprov:switch-aprovisionamiento:1.0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="urn:com.ec.tvcable.switch_aprov:switch-aprovisionamiento:1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="urn:com.ec.tvcable.switch_aprov:switch-aprovisionamiento:1.0" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="urn:com.ec.tvcable.switch_aprov:switch-aprovisionamiento:1.0">
  <xsd:element name="aprovisionar" type="tns:aprovisionar"/>
  <xsd:complexType name="aprovisionar">
    <xsd:sequence>
      <xsd:element minOccurs="0" name="string" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="aprovisionarResponse" type="tns:aprovisionarResponse"/>
  <xsd:complexType name="aprovisionarResponse">
    <xsd:sequence>
      <xsd:element minOccurs="0" name="string" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>
  </wsdl:types>
  <wsdl:message name="aprovisionarResponse">
    <wsdl:part name="parameters" element="tns:aprovisionarResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="aprovisionar">
    <wsdl:part name="parameters" element="tns:aprovisionar">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="AprovisionamientoPortType">
    <wsdl:operation name="aprovisionar">
      <wsdl:input name="aprovisionar" message="tns:aprovisionar">
    </wsdl:input>
      <wsdl:output name="aprovisionarResponse" message="tns:aprovisionarResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="AprovisionamientoSoapBinding" type="tns:AprovisionamientoPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="aprovisionar">
      <soap:operation soapAction="aprovisionar" style="document"/>
      <wsdl:input name="aprovisionar">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="aprovisionarResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Aprovisionamiento">
    <wsdl:port name="AprovisionamientoPort" binding="tns:AprovisionamientoSoapBinding">
      <soap:address location="http://localhost:8080/switch-aprovisionamiento/Aprovisionamiento"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
