package com.ec.tvcable.switchaprov.AprovDTH;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.6
 * 2016-02-11T10:56:25.956-05:00
 * Generated source version: 2.6.6
 * 
 */
@WebServiceClient(name = "TvCableIntegrationServiceInternal", 
                  wsdlLocation = "file:/C:/Users/wamorales/workspace/switch-aprovisionamiento/src/main/resources/wsdl/WsdlDTH.wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class TvCableIntegrationServiceInternal extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "TvCableIntegrationServiceInternal");
    public final static QName TvCableIntegrationServiceInternalSoap12 = new QName("http://tempuri.org/", "TvCableIntegrationServiceInternalSoap12");
    public final static QName TvCableIntegrationServiceInternalSoap = new QName("http://tempuri.org/", "TvCableIntegrationServiceInternalSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/wamorales/workspace/switch-aprovisionamiento/src/main/resources/wsdl/WsdlDTH.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TvCableIntegrationServiceInternal.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/wamorales/workspace/switch-aprovisionamiento/src/main/resources/wsdl/WsdlDTH.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TvCableIntegrationServiceInternal(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TvCableIntegrationServiceInternal(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TvCableIntegrationServiceInternal() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TvCableIntegrationServiceInternal(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TvCableIntegrationServiceInternal(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TvCableIntegrationServiceInternal(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns TvCableIntegrationServiceInternalSoap
     */
    @WebEndpoint(name = "TvCableIntegrationServiceInternalSoap12")
    public TvCableIntegrationServiceInternalSoap getTvCableIntegrationServiceInternalSoap12() {
        return super.getPort(TvCableIntegrationServiceInternalSoap12, TvCableIntegrationServiceInternalSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TvCableIntegrationServiceInternalSoap
     */
    @WebEndpoint(name = "TvCableIntegrationServiceInternalSoap12")
    public TvCableIntegrationServiceInternalSoap getTvCableIntegrationServiceInternalSoap12(WebServiceFeature... features) {
        return super.getPort(TvCableIntegrationServiceInternalSoap12, TvCableIntegrationServiceInternalSoap.class, features);
    }
    /**
     *
     * @return
     *     returns TvCableIntegrationServiceInternalSoap
     */
    @WebEndpoint(name = "TvCableIntegrationServiceInternalSoap")
    public TvCableIntegrationServiceInternalSoap getTvCableIntegrationServiceInternalSoap() {
        return super.getPort(TvCableIntegrationServiceInternalSoap, TvCableIntegrationServiceInternalSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TvCableIntegrationServiceInternalSoap
     */
    @WebEndpoint(name = "TvCableIntegrationServiceInternalSoap")
    public TvCableIntegrationServiceInternalSoap getTvCableIntegrationServiceInternalSoap(WebServiceFeature... features) {
        return super.getPort(TvCableIntegrationServiceInternalSoap, TvCableIntegrationServiceInternalSoap.class, features);
    }

}
